dist: bionic
language: node_js
node_js:
  - 8

before_install:
  - mkdir .tmp
  - cd .tmp
  - bash <(curl -fsSL https://raw.githubusercontent.com/tboox/xmake/master/scripts/get.sh)
  - source ~/.xmake/profile
  - wget https://github.com/lc-soft/LCUI/archive/develop.zip -O LCUI-develop.zip
  - unzip LCUI-develop.zip
  - rm LCUI-develop.zip
  - cd LCUI-develop
  - sh ./autogen.sh
  - ./configure
  - make
  - sudo make install
  - cd ../..
  - rm -rf .tmp
  - npm install

before_script:
  - ./node_modules/.bin/commitlint-travis

script:
  - commitlint-travis
  - npm link
  - tradc --version
  - tradc example/src/app.jsx
  - mkdir example/build
  - cd example/build
  - cmake ../
  - make
